dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake-data
      - cmake
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir bld && cd bld && cmake .. && cmake --build .
